Sdk delivery refactor
EkoLabs/eko-js-sdk pull request #11
Opened 2020-12-13 11:45 UTC by eyal-avital

this refactor purpose is that the SDK could work also with delivery3.0.

- changed ekoPlayer constructor - construct this.ekoEmbed with ekoEmbed factory ,to expose different behaviour.
- ekoEmbed/v1 - old version api (baloo)
- ekoEmbed/v2 - new version api (delivery)

- refactor cover with cover factory

- iframeCreator.js control the iframe instanceCount

- update tests -  integration tests use puppeteer for testing ekoPlayer api

*** i still need to change package.json version***

2020-12-14 04:54 UTC, Melatonin64 commented on src/EkoPlayer.js
> +import coverFactory from './lib/cover/coverFactory';
Might be a bit nit picky, so feel free to ignore, but we should consider changing the filename for consistency (i.e. `ekoEmbed/factory` vs. `cover/coverFactory`).

2020-12-14 04:55 UTC, Melatonin64 commented on src/EkoPlayer.js
>       * @param {Element|string} el - The container element to be used by the player, or a DOM selector string for the container element.
Missing the new param `embedapi` documentation in the JSDoc comment.

2020-12-14 06:06 UTC, Melatonin64 requested changes
Overall looks really great, thanks @eyal-avital!
Let's fix these comments and do another round of review - thanks!

2020-12-14 06:06 UTC, Melatonin64 commented on src/lib/ekoEmbed/factory.js
> +    const ekoEmbed = imples[embedapiVersion];
Consider changing to `const EkoEmbedClass`

2020-12-14 06:06 UTC, Melatonin64 commented on src/lib/ekoEmbed/v2.js
> +        this.eventEmitter.emit(msg.event, msg.args, msg.embedid, msg.embedapi);
We should also add tests to verify that both V1 and V2 behave consistently and as expected/documented...

2020-12-17 19:10 UTC, Melatonin64 requested changes
Looks good to me, next steps would be:

- Suggested fix (spread operator)
- README changes - we should we document the new 2nd arg (embedapi) of the load() method in the README
- Test cover the event functionality (to make sure args are passing as expected for v1 and v2 consistently).

2020-12-17 19:10 UTC, Melatonin64 commented on src/lib/ekoEmbed/v1.js
> +        this.trigger(msg.type.replace(/^eko./, ''), msg.args);
```suggestion
        this.trigger(msg.type.replace(/^eko./, ''), ...msg.args);
```

2020-12-17 19:10 UTC, Melatonin64 commented on src/lib/ekoEmbed/v1.js
> +        this.trigger(msg.type.replace(/^eko./, ''), msg.args);
I think we need the spread operator here to get the desired result.
@eyal-avital can we add tests to make sure that the arguments are being passed correctly?

2020-12-17 19:45 UTC, DivyaMahadevan commented
Looks really good! Agree with Tomer that it would be good to have some tests around args being passed correctly, but other than that it looks good to me.

2020-12-20 15:21 UTC, Melatonin64 reviewed
Requested a tiny change in the README, otherwise looks great!!

2020-12-20 15:21 UTC, Melatonin64 commented on README.md
> +| embedapi | `1.0, 2.0` | embed api version to be used internally. |
```suggestion
| embedapi | `String` | Optional. eko embed api version to be used internally. Valid values include `"1.0"`, `"2.0"`. If no value given, default value `"1.0"` will be used. |
```

2020-12-21 04:50 UTC, Melatonin64 approved these changes
Looks good to me, let's merge!
(Note to self - let's add and maintain a CHANGELOG file).

2020-12-21 04:52 UTC, merged